/////////////////////////////////////////////////////////////////////////////////////////////
//
//	File Name:		timer.c
//	Author(s):		Jeffery Bahr, Dmitriy Antonets
//	Copyright Notice:	Copyright, 2019, Ping LLC
//
//	Purpose/Functionality:	System timer functions
//
/////////////////////////////////////////////////////////////////////////////////////////////

#include "app_config.h"

// Definitions for FreeRTOS prototypes, macros and declarations
//#include "FreeRTOS.h"
//#include "semphr.h"

//  Support for NRF Log Functions 
#include "nrf_log.h"

// Definitions for prototypes, macros and declarations -- Ping-Specific

#define ARM_MATH_CM4

#include "arm_math.h"
#include "arm_const_structs.h"

#include "ping_config.h"

#include "timer.h"

/////////////////////////////////////////////////////////////////////////////////////////////
//  Defines                                                                                                                                               //
/////////////////////////////////////////////////////////////////////////////////////////////



/////////////////////////////////////////////////////////////////////////////////////////////
//  Variable and Data Structure Declarations                                                                                               //
/////////////////////////////////////////////////////////////////////////////////////////////

uint32_t global_msec_counter = 0;

/////////////////////////////////////////////////////////////////////////////////////////////
//  Function Prototypes                                                                                                                              //
/////////////////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////////////////////
//  Code Begins                                                                                                                                        //
/////////////////////////////////////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////////////
//
// The ElapsedTimeInMilliseconds function returns the elapsed time in msec
//
//////////////////////////////////////////////////////////////////////////////

uint32_t ElapsedTimeInMilliseconds(void)
{
	return global_msec_counter  * (TIMER1_REPEAT_RATE / 1000);
}

//////////////////////////////////////////////////////////////////////////////
//
// The Timer1_Init() function initializes the nRF52 timer, which we use to keep track of real time.
//
// Parameter(s):
//
//	repeat_rate		number of microseconds between timer interrupts
//
//////////////////////////////////////////////////////////////////////////////

void Timer1_Init(uint32_t repeat_rate)
{

	NRF_TIMER1->TASKS_STOP = 1;

	// Create an Event-Task shortcut to clear Timer 1 on COMPARE[1] event.
	NRF_TIMER1->SHORTS = (TIMER_SHORTS_COMPARE0_CLEAR_Enabled << TIMER_SHORTS_COMPARE0_CLEAR_Pos);
	NRF_TIMER1->MODE = TIMER_MODE_MODE_Timer;
	NRF_TIMER1->BITMODE = (TIMER_BITMODE_BITMODE_16Bit << TIMER_BITMODE_BITMODE_Pos);
	NRF_TIMER1->PRESCALER = 4; // 1us resolution
	NRF_TIMER1->INTENSET |= (TIMER_INTENSET_COMPARE0_Set << TIMER_INTENSET_COMPARE0_Pos);

	// Sample update needs to happen as soon as possible. The earliest possible moment is MAX_SAMPLE_LEVELS
	// ticks before changing the output duty cycle.
	
	NRF_TIMER1->CC[0] = repeat_rate;
	NRF_TIMER1->TASKS_START = 1;

	// Timer1 enable interrupt.

	NVIC_EnableIRQ(TIMER1_IRQn);
}

//////////////////////////////////////////////////////////////////////////////
//
// The TIMER1_IRQHandler() function is the event-handler for a timer interrupt.  It updates
// a number of global variables with the current time.
//
// Some of the counters are reset by individual routines, such as timer_lights_event.  This
// is a holdover from when the firmware was non-tasking.
//
//////////////////////////////////////////////////////////////////////////////

void TIMER1_IRQHandler(void)
{
	// Check if Timer 1 interrupts are enabled and if this interrupt is generated by Timer 1.
	if ((NRF_TIMER1->EVENTS_COMPARE[0] != 0) &&
		(NRF_TIMER1->INTENSET | (TIMER_INTENSET_COMPARE0_Set << TIMER_INTENSET_COMPARE0_Pos)))
	{
		NRF_TIMER1->EVENTS_COMPARE[0] = 0;

		global_msec_counter++;

	}
}


